# Generated by Django 4.2.7 on 2024-03-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='poetsShown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poetAuthor', models.CharField(max_length=60)),
                ('poetName', models.CharField(max_length=60)),
                ('poetContext', models.TextField(max_length=4000)),
            ],
        ),
    ]
