# Generated by Django 4.2.7 on 2024-03-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetsShown', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poet_author',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='poets_shown',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='poets_shown',
            old_name='poetAuthor',
            new_name='poet_author',
        ),
        migrations.AlterField(
            model_name='poets_shown',
            name='poetName',
            field=models.CharField(db_column='poetName', max_length=60),
        ),
        migrations.RenameField(
            model_name='poets_shown',
            old_name='poetName',
            new_name='poet_name',
        ),
        migrations.RemoveField(
            model_name='poets_shown',
            name='poetContext',
        ),
        migrations.AddField(
            model_name='poets_shown',
            name='poet_context',
            field=models.TextField(db_column='poetContext', default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='poet_author',
            table='poetsShown_poet_author',
        ),
        migrations.AlterModelTable(
            name='poets_shown',
            table='poetsShown_poets_shown',
        ),
    ]
